[sc-131251] Add option to change maxCount value
dataiku/dss-plugin-osisoft pull request #25
Opened 2023-04-14 15:19 UTC by alexbourret

2023-11-20 14:50 UTC, liamlynch-data requested changes
Have tested it on all the relevant components and looked at the code. 

For the Recorded data type it's all good - the `max_count` param does what is expected and changes the numbers of results coming back. 

For the Interpolated and Plot data type `maxCount` query param does not do anything at the API level of OsiSoft (it is not active for these endpoints) so it has no effect in the plugin either, so I don't think we should be adding it here.

For the Interpolated type, I think the interpolation params directly determine the number of results per path within the time range given, so that is all we need I think.

For Plot, the `intervals` param (plural) determines how many slices of the time dimension sampling occurs on so directly determines the number of results (if I understand correctly - see [here](https://docs.aveva.com/bundle/pi-web-api-reference/page/help/controllers/stream/actions/getplot.html))

So I think we should remove the `max_count` for both Interpolated and Plot and maybe add in the `intervals` one for Plot  at some point (if we think people will need it).

2023-11-20 18:16 UTC, alexbourret commented on python-connectors/pi-system_piwebapi-toolbox/connector.py
> +                endpoint_type="AF", max_count=self.max_count
👍 fixed in [3e75509](https://github.com/dataiku/dss-plugin-osisoft/pull/35/commits/3e755093ad692bc653b7f9e9b7aba9faf304f039)

2023-11-20 18:17 UTC, alexbourret commented
maxCount selector visibility is now fixed with this commit : [c44678d](https://github.com/dataiku/dss-plugin-osisoft/pull/35/commits/c44678d823fcc533dff222f0f912c80d97dc8cd6)

2023-11-21 09:41 UTC, liamlynch-data commented
I took a look at the changes in the destination branch (feature/sc-131263-add-time-span-filters-to-ef-search), all looks good to me.

2023-11-21 09:41 UTC, liamlynch-data approved these changes

2023-12-08 17:22 UTC, merged